import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderColor: '#ccc',
    borderWidth: 1,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  tab: {
    paddingVertical: 9,
    paddingHorizontal: 26,
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 15,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: '#cdedffff',
    borderWidth: 2,
    borderColor: '#01a2ffff',
  },
  tabText: {
    color: '#ccc',
    fontSize: 15,
    fontWeight: 'bold',
  },
  activeTabText: {
    color: '#01a2ffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  cardPreview: {
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImage: {
    width: 80,
    height: 75,
    borderRadius: 12,
    borderColor: '#aaa',
    borderWidth: 1,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  libraryImage: {
    borderRadius: 12,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  boardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  boardCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    borderColor: '#aaa',
    borderWidth: 1,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  boardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  boardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    top: 5,
    left: 5,
    paddingBottom: 3,
  },
  buttonColumn: {
    gap: 40,
  },
  deleteIcon: {
    color: '#999',
    fontSize: 22,
    fontWeight: 'bold',
    lineHeight: 18,
    position: 'absolute',
    top: 9,
    right: 2,
  },
  overlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    alignItems: 'center',
    borderRadius: 10, 
  },
  overlayText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 45,
    fontWeight: 'bold',
  },
  shadowWrapper: {
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.7,
    shadowRadius: 2.5,
    elevation: 4,
    marginHorizontal: 7,
    marginVertical: 6,
  },
  imageWrapper: {
    borderRadius: 12,
    overflow: 'hidden', // keeps rounded corners
  },
});
