import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderColor: '#ccc',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  tab: {
    paddingVertical: 9,
    paddingHorizontal: 28,
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  activeTab: {
    backgroundColor: '#cdedffff',
    borderWidth: 2,
    borderColor: '#01a2ffff',
  },
  tabText: {
    color: '#ccc',
    fontSize: 15,
    fontWeight: 'bold',
  },
  activeTabText: {
    color: '#01a2ffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  cardPreview: {
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 7,
    marginVertical: 6,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2.5,
    elevation: 3,
  },
  cardImage: {
    width: 80,
    height: 75,
    borderRadius: 12,
    borderColor: '#aaa',
    borderWidth: 1,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  libraryImage: {
    borderRadius: 12,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  boardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  boardCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    borderColor: '#aaa',
    borderWidth: 1,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 2.5,
    elevation: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
  },
  cardWrapper: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    overflow: 'visible',
  },
  cardBody: {
    flex: 1,
  },
  boardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  boardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    top: 5,
    left: 5,
    paddingBottom: 3,
  },
  buttonColumn: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  deleteButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    padding: 6,
  },
  deleteIcon: {
    color: '#999',
    fontSize: 22,
    fontWeight: 'bold',
    lineHeight: 18,
  },
  overlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    alignItems: 'center',
    borderRadius: 10, 
  },
  overlayText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 45,
    fontWeight: 'bold',
  },
  headerRow: {
    paddingHorizontal: 6,
  },
  imageWrapper: {
    borderRadius: 12,
    overflow: 'hidden', // keeps rounded corners
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
    gap: 6,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  emptySubtitle: {
    fontSize: 14,
    color: '#555',
  },
});
