import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 40,
  },
  wrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tick: {
    width: 30,
    height: 30,
  },
  textRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  textTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingBottom: 5,
  },
  column: {
    flexDirection: 'column',
    alignItems: 'center',
    marginVertical: 8,
    gap: 2,
  },
  card: {
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 20,
    alignItems: 'center',
    backgroundColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 5,
    paddingTop: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  image: {
    width: '85%',
    height: '80%',
    borderRadius: 8,
    resizeMode: 'contain',
    borderWidth: 1,
    borderColor: '#333',
  },
  label: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  placeholder: {
    fontSize: 18,
    color: '#aaa',
  },
    saveButton: {
    flex: 1,
    marginLeft: 8,
    padding: 6,
    backgroundColor: '#cdedffff',
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#38b6ff',
  },
  slideshowButton: {
    flex: 1,
    marginLeft: 8,
    padding: 8,
    backgroundColor: '#e0e1e2ff',
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#727272ff',
  },
  saveText: {
    color: '#aaa', 
    fontSize: 15, 
    fontWeight: 'bold',
    textAlign: 'center',
  },
  slideshowText: {
    color: '#727272ff', 
    fontSize: 15, 
    fontWeight: 'bold',
    textAlign: 'center',
  },
});