import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  card: {
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 10,
    backgroundColor: '#fff',
    position: 'relative',
    marginHorizontal: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 7,
    elevation: 4,
  },
  deleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 15,
    borderColor: '#ccc',
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  deleteText: {
    color: '#ccc',
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 18,
  },
  cardContent: {
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 22,
    paddingBottom: 8,
  },
  image: {
    width: 200,
    height: 180,
    borderRadius: 10,
    marginBottom: 8,
  },
  placeholder: {
    width: 200,
    height: 180,
    borderRadius: 10,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  placeholderText: {
    color: '#666',
    fontSize: 15,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dragHandle: {
    position: 'absolute',
    top: 6,
    left: 6,
    zIndex: 2,
    borderRadius: 16,
    paddingHorizontal: 6,
    paddingTop: 0.5,
    paddingBottom: 2,
    borderColor: '#ccc',
    borderWidth: 2,
  },
  dragText: {
    fontSize: 17,
    color: '#ccc',
  },
  addEmptySlotButton: {
    flex: 1,
    alignSelf: 'center',
    backgroundColor: '#38b6ff',
    padding: 8,
    paddingVertical: 16,
    alignItems: 'center', 
    borderRadius: 12,
    marginBottom: 80,
  },
  saveButton: {
    flex: 1,
    marginLeft: 8,
    padding: 8,
    backgroundColor: '#38b6ff',
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 80,
  },
  slideshowButton: {
    flex: 1,
    marginLeft: 8,
    padding: 8,
    backgroundColor: '#000',
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 80,
  },
  buttonText: {
    color: 'white', 
    fontSize: 15, 
    fontWeight: 'bold',
    textAlign: 'center',
  },

  // title chooser

  chooserTop: {
    paddingHorizontal: 16,
    paddingTop: 65,
  },
  chooserTextInput: {
    padding: 9,
    backgroundColor: '#eee',
    borderRadius: 12,
    marginBottom: 12,
    marginHorizontal: 10,
    fontSize: 17,
    color: '#111',
  },
});