import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 60,
    paddingHorizontal: 10,
  },
  card: {
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 12,
    marginTop: 12,
    marginBottom: 10,
    backgroundColor: '#fff',
    position: 'relative',
    marginHorizontal: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 4,
  },
  deleteButton: {
    position: 'absolute',
    top: 7,
    right: 1,
    width: 24,
    height: 24,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  deleteText: {
    color: '#ccc',
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 18,
  },
  cardContent: {
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 22,
    paddingBottom: 8,
  },
  image: {
    width: 210,
    height: 180,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  placeholder: {
    width: 190,
    height: 180,
    borderRadius: 10,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  placeholderText: {
    color: '#aaa',
    fontSize: 18,
  },
  title: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dragHandle: {
    position: 'absolute',
    top: 3,
    left: 1,
    zIndex: 2,
    borderRadius: 16,
    paddingHorizontal: 6,
    paddingTop: 0.5,
    paddingBottom: 2,

  },
  dragText: {
    fontSize: 25,
    color: '#ccc',
  },
  saveButton: {
    width: '40%',
    paddingVertical: 7,
    borderRadius: 12,
    marginTop: 15,
    marginBottom: 28,
    alignItems: 'center',
    backgroundColor: '#38b6ff',
    borderWidth: 2,
    borderColor: '#38b6ff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  saveText: {
    color: '#fff', 
    fontSize: 16, 
    fontWeight: 'bold',
    textAlign: 'center',
  },

  // title chooser

  chooserTop: {
    paddingHorizontal: 16,
    paddingTop: 65,
  },
  chooserTextInput: {
    padding: 9,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 12,
    marginHorizontal: 10,
    fontSize: 17,
    color: '#111',
    borderColor: '#ccc',
    borderWidth: 1,
  },
});